### ISSUE TITLE
using the discovery without port specified

### ISSUE THREAD

**Issue by maklei125** [feross/torrent-discovery#7]
is the port required even for dht? I want to use it without the tracker.
port: 0     // torrent client port (only required in node), why for node only?
In node, peer is a string in the form 12:34:56:78:4000 why, any additional info?
thanks.

**Comment by feross** [comment]
The port is required because it tells peers which port your torrent client is listening on.

When you announce to the DHT to join a swarm, the peers you announce to can figure out what your IP address is by looking at the UDP packet, but they can't figure out which TCP port your torrent client is listening on unless you tell them. :)

It's only required in node because in the browser, we use WebRTC which works completely differently. The client doesn't actually listen on a port in the traditional sense.
